version: 2
jobs:

  build:
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      SCRATCH: "/scratch"
    docker:
      - image: circleci/python:3.7

    working_directory: /tmp/src/fw-heudiconv

    steps:
      - checkout
      - run:
          name: install dependencies
          # install conda, validator
          command: |
            cd /tmp
            export MINICONDA=/tmp/miniconda
            export PATH="$MINICONDA/bin:$PATH"
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -f -p $MINICONDA
            conda config --set always_yes yes
            conda update conda
            conda info -a
            conda create -n flywheel python=3.7
            source activate flywheel
            conda install -c conda-forge -y datalad
            # Add nodejs and the validator
            conda install nodejs
            npm install -g yarn && \
            mkdir -p /tmp/validator && \
            cd /tmp/validator && \
            git clone  -b 'master' --single-branch --depth 1 \
                --single-branch https://github.com/bids-standard/bids-validator.git  && \
            cd /tmp/validator/bids-validator && \
            yarn --ignore-engines && \
            cd bids-validator && npm install -g

      # install package
      - run:
          name: Install fwheudiconv
          command: |
            export PATH=/tmp/miniconda/bin:$PATH
            conda activate flywheel
            pip install .[all]
      # Step 3: run pytests
      - run:
          name: run tests
          command: |
            conda activate flywheel
            pytest -v --cov testing/
